import type { CreationAnswers, CreationPlan, PlanAction, ProjectTemplate } from './domain'

function hash(value: string): string {
  let result = 2166136261
  for (let index = 0; index < value.length; index++) result = Math.imul(result ^ value.charCodeAt(index), 16777619)
  return (result >>> 0).toString(16).padStart(8, '0')
}

/** Keeps the generated action graph in dependency order. */
// eslint-disable-next-line sonarjs/cognitive-complexity
export function planCreation(template: ProjectTemplate, answers: CreationAnswers): CreationPlan {
  const actions: PlanAction[] = []
  const epicLabel = (name: string) => name.includes(': ') ? name.slice(name.indexOf(': ') + 2) : name
  const labelKey = (name: string) => name.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  const add = (kind: PlanAction['kind'], key: string, title: string, marker: string, dependsOn: string[] = [], data?: PlanAction['data']) => actions.push(data ? { kind, key, title, marker, dependsOn, data } : { kind, key, title, marker, dependsOn })
  if (answers.repositoryMode === 'create')
    add('repository', 'repository', `Create ${answers.owner}/${answers.repository}`, `repository:${answers.owner}/${answers.repository}`, [], { owner: answers.owner, name: answers.repository, private: answers.privateRepository })
  add('project', 'project', `Create Project for ${template.name}`, `project:${template.id}`, answers.repositoryMode === 'create' ? ['repository'] : [], { title: template.name, description: `Generated by generate-project-kanban\nmarker: project:${template.id}` })
  add('field', 'field-status', 'Configure built-in Status field', `field:${template.id}:Status:Todo,In Progress,Done`, ['project'], { name: 'Status', options: ['Todo', 'In Progress', 'Done'] })
  add('field', 'field-week', 'Create Week field', `field:${template.id}:Week`, ['project'], { name: 'Week', options: ['Week 1', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6'] })
  add('field', 'field-epic', 'Create Epic field', `field:${template.id}:Epic`, ['project'], { name: 'Epic', options: template.epics.map(epic => epic.name) })
  add('field', 'field-priority', 'Create Priority field', `field:${template.id}:Priority`, ['project'], { name: 'Priority', options: ['P0', 'P1', 'P2', 'P3'] })
  const labels = [...template.epics.map(epic => epic.name), 'Epic', 'Story', 'Assessment', 'Functional', ...new Set(template.stories.map(story => `Category: ${story.category}`)), ...(template.stories.some(story => story.category === 'security') ? ['Security'] : [])]
  if (labels.some(label => label.length > 50))
    throw new Error('Generated labels must be at most 50 characters')
  if (template.stories.some(story => ['Story', 'Functional', `Category: ${story.category}`, ...(story.category === 'security' ? ['Security'] : [])].length > 4))
    throw new Error('Generated issues may have at most four labels')
  for (const label of labels) add('label', `label-${labelKey(label)}`, `Ensure label: ${label}`, `label:${template.id}:${label}`, [answers.repositoryMode === 'create' ? 'repository' : 'project'], { name: label.startsWith('Category: ') ? label : epicLabel(label) })
  for (const epic of template.epics) add('epic', `epic-${epic.id}`, `Create epic: ${epic.name}`, `epic:${template.id}:${epic.id}`, ['project', `label-${labelKey(epic.name)}`], { title: epic.name, body: `## Epic user story\nAs a ${epic.role}, I want to ${epic.action}, so that ${epic.benefit}.\n\n${epic.description}`, label: epicLabel(epic.name), labels: ['Epic', 'Functional'] })
  for (const story of template.stories) {
    const storyLabels = ['Story', 'Functional', `Category: ${story.category}`, ...(story.category === 'security' ? ['Security'] : [])]
    add('story', `story-${story.id}`, `Create story: ${story.title}`, `story:${template.id}:${story.id}`, [`epic-${story.epicId}`, 'label-story'], { title: story.title, body: `## User story\nAs a ${story.role}, I want to ${story.action}, so that ${story.benefit}.\n\n## Acceptance criteria\n${story.acceptanceCriteria.map(criterion => `- [ ] ${criterion}`).join('\n')}`, week: story.week, priority: story.priority, epicId: story.epicId, labels: storyLabels })
    add('relationship', `relationship-${story.id}`, `Link story to ${story.epicId}`, `relationship:${template.id}:${story.id}`, [`story-${story.id}`, `epic-${story.epicId}`])
  }
  for (const assessment of template.assessments) add('assessment', `assessment-${assessment.id}`, `Create ${assessment.title} (${assessment.weight}%)`, `assessment:${template.id}:${assessment.id}`, ['project', 'label-assessment'], { title: assessment.title, body: `Checkpoint: Week ${assessment.week}\nGrade weight: ${assessment.weight}%`, week: assessment.week, weight: assessment.weight, label: 'Assessment' })
  for (const action of actions.filter(item => ['epic', 'story', 'assessment'].includes(item.kind))) {
    const source = action.kind === 'story' ? template.stories.find(story => `story-${story.id}` === action.key) : undefined
    const assessment = action.kind === 'assessment' ? template.assessments.find(item => `assessment-${item.id}` === action.key) : undefined
    add('item', `item-${action.key}`, `Add ${action.title} to project`, `item:${action.marker}`, [action.key, 'project'], {
      contentKind: action.kind,
      ...(source ? { week: `Week ${source.week}`, epic: template.epics.find(epic => epic.id === source.epicId)?.name ?? '', priority: source.priority } : {}),
      ...(assessment ? { week: `Week ${assessment.week}`, assessmentWeight: assessment.weight } : {}),
    })
  }
  const ownerLogin = answers.owner.trim().replace(/^@/, '').toLowerCase()
  const collaboratorLogin = answers.inviteCollaborator?.trim().replace(/^@/, '').toLowerCase()
  if (answers.repositoryMode === 'create' && answers.inviteCollaborator && ownerLogin !== collaboratorLogin)
    add('invitation', 'invitation', `Invite @${answers.inviteCollaborator}`, `invitation:${answers.owner}/${answers.repository}:${answers.inviteCollaborator}`, ['repository'], { login: answers.inviteCollaborator })
  const canonical = JSON.stringify({ template: template.id, answers, actions })
  const fingerprint = hash(canonical)
  return { fingerprint, templateId: template.id, answers, actions }
}
